### ISSUE TITLE
Error: spawn java ENOENT thrown

### ISSUE THREAD

**Issue by prekolna** [Medium/local-dynamo#32]
I'm trying to start local-dynamo in a gulp task, and I'm getting this error:
```shell
Error: spawn java ENOENT
  at exports._errnoException (util.js:837:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at doNTCallback2 (node.js:429:9)
  at process._tickCallback (node.js:343:17)
  at Function.Module.runMain (module.js:477:11)
  at startup (node.js:117:18)
  at node.js:951:3
```

The gulp task looks like:
```javascript
gulp.task('launch-dev-db', function() {
  var localDynamo = require('local-dynamo');
  localDynamo.launch(paths.db, 3456);
});
```

I logged out the PATH that was being supplied to `child_process.spawn`, and it has `/usr/bin/` included, which is where java is:
```shell
» file $(which java)
/usr/bin/java: symbolic link to `/etc/alternatives/java'
```

I'm on node 4.0.0 and Ubuntu 14.04.

**Comment by gswalden** [comment]
This happened to me, but once I created the data directory (`/database/dir` in the docs) the error went away.
